# author: Nexora Studios
# discord: https://discord.gg/qf4FekKS
# description: Professional Gradient Name Plugin For Free | Developed by Nexora Studios
# ===============================
# Placeholder Settings
# ===============================
placeholders:
  enabled: true
  gradient_name_placeholder: "%nxnamegradient_name%"

config-version: "1.2"
version-check: false
startup-banner: true

storage:
  type: "sqlite" # sqlite | yaml
  sqlite:
    file: "data.db"

settings:
  auto-apply-on-join: true
  apply-to-displayname: true
  apply-to-tablist: true

gui:
  showgradientid: false # if true shows "(id)" after gradient name in GUI item display

cooldown-seconds: 2

blacklist:
  worlds: []
  regions: []
  players: []
  blocked-permissions: []

debug: false
